version: "3.9"

services:
  app:
    build: .
    container_name: business_advisor_app
    ports:
      - "8501:8501"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:sujal123@db:5432/businessdb

  db:
    image: postgres:14
    container_name: business_advisor_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sujal123
      POSTGRES_DB: businessdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:
